### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by lissertations** [hughrun/pickpocket#2]
Hi, pickpocket is awesome! Just a couple of small typo bug things:

- The consumer key needs to be pasted at line 50, not line 51 (as per readme.md)
- On line 26, `pip requests` didn't work, but `pip install requests` did (ditto for `pip3 requests`)
- On line 97, 'paramater' should be 'parameter'
- And idk what 'iterate over the keys' means on line 126, but that's not really a bug, I just don't get stuff

**Comment by hughrun** [comment]
Oops, sorry @lissertations - thanks for logging these. I'll make some edits. The phrasing used at 126 just means 'check every item in the dictionary one by one', noting that 'item' will return each 'key' rather than its 'value' (see [this explanation](https://stackoverflow.com/questions/3294889/iterating-over-dictionaries-using-for-loops)) I can see how it's not particularly clear though, I'll reword.
